Initial setting
OlhaKolos/atap-report-portal pull request #3
Opened 2023-04-25 20:37 UTC by OlhaKolos

2023-04-27 07:58 UTC, ihor-dynka requested changes

2023-04-27 07:58 UTC, ihor-dynka commented on .gitignore
> +# Sensitive or high-churn files
you can just specify entire folder .idea/

2023-04-27 07:58 UTC, ihor-dynka commented on src/main/java/pom/components/AbstractFragment.java
> +
if the name contains Abstract then make the class abstract

2023-04-27 10:46 UTC, NovoDan commented on .gitignore
> +.idea/**/dataSources/
add whole .idea folder instead separate inner folders

2023-04-27 10:46 UTC, NovoDan commented on src/test/java/TestExample.java
> +@Test()
brackets are redundant here

2023-05-01 15:16 UTC, NovoDan approved these changes

2023-05-02 14:44 UTC, ihor-dynka approved these changes

2023-05-03 08:53 UTC, merged